version : "3"

services:
    front-end:
        build:
            context: ./frontend
    
    back-end:
        build:
            context: ./backend
    
    reverse-proxy:
        build:
            context: ./reverseProxy
        ports:
            - 80:80
        depends_on:
            - back-end
            - front-end